sudo: required
language: node_js
node_js:
- '4.2.2'
before_install:
 - gem install ruby 
 - npm install -g npm
 - npm install promise
before_script:
  - npm install -g gulp
script: 
 - npm test 
 - gulp coveralls
 - gulp deploy 
